sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t brandonnguyendocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brandonnguyendocker/react-test npm test

after_success:
  - docker build -t brandonnguyendocker/multi-client ./client
  - docker build -t brandonnguyendocker/multi-nginx ./nginx
  - docker build -t brandonnguyendocker/multi-server ./server
  - docker build -t brandonnguyendocker/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push brandonnguyendocker/multi-client
  - docker push brandonnguyendocker/multi-nginx
  - docker push brandonnguyendocker/multi-server
  - docker push brandonnguyendocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-954976304728'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY   